version: "3.9"

services:
  db:
    image: postgres:16
    container_name: notes_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_password
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - notes_db_data:/var/lib/postgresql/data

volumes:
  notes_db_data:
